export type User = {
  id: number;
  first_name: string;
  last_name: string;
  dob: string;
  email: string;
  username: string;
  status: "active" | "inactive" | "suspended";
  phone: string;
  gender: "Male" | "Female" | "Other";
  street_address_1: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  avatar: string | null;
  kyc_status: "unverified" | "pending" | "verified";
  fingerprint: string;
  promo_code: string | null;
  promotion_type: string | null;
  deposit_count: number;
  tickets: number;
  language: string;
  timezone: string;
  mautic_contact_id: number;
  email_verified_at: string | null;
  created_at: string;
  updated_at: string;
  total_balance: string;
  balance: string;
  bonus_balance: string;
  cashback: string;
  currency: string;
};
