import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/layout/header";
import Sidebar from "../components/layout/sidebar";
import Footer from "../components/layout/footer";

import { SidebarProvider } from "../components/layout/SidebarContext";
import LayoutContent from "../components/layout/LayoutContent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bounded = localFont({
  src: [
    {
      path: "../public/fonts/Bounded-regular.ttf", // Changed path
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Bounded-extralight.ttf", // Changed path
      weight: "200", // ExtraLight is typically 200, not 700
      style: "normal",
    },
  ],
  variable: "--font-bounded",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={bounded.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bounded.variable} bg-[#061621]`}
      >
        {children}
      </body>
    </html>
  );
}
