import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/header";

import Sidebar from "../components/layout/sidebar";
import Footer from "../components/layout/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#061621]`}
      >
        <Header />
        <div className="grid lg:grid-cols-4 grid-cols-1 bg-[#061621] mb-6  lg:gap-8 px-4">
          <div className="lg:block hidden">
            <Sidebar />
          </div>
          <div className="lg:col-span-3 col-span-4">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
