import { Game } from "./types";

export const gameCardData: Game[] = [
  {
    id: 42474,
    game_name: "*NSYNC Pop",
    provider: "PlayNgo",
    api_provider: "Ryan",
    thumbnail: "https://cdn2.softswiss.net/i/s3/playngo/NSYNCPop.webp",
    demo: 0,
    slug: "318995864-*nsync-pop",
    rtp: "88.8",
    no_dep_bonus: 0,
    lock_game: true,
  },
  {
    id: 41981,
    game_name: "1 Reel - Queen Of Water",
    provider: "Spinomenal",
    api_provider: "Ryan",
    thumbnail:
      "https://cdn2.softswiss.net/i/s3/spinomenal/1ReelQueenOfWater.webp",
    demo: 1,
    slug: "71293042-1-reel---queen-of-water",
    rtp: "100.10",
    no_dep_bonus: 0,
    lock_game: false,
  },
  {
    id: 17408,
    game_name: "Fortuna De Los Muertos 3",
    provider: "Spinomenal",
    api_provider: "Ryan",
    thumbnail:
      "https://cdn2.softswiss.net/bets/i/s3/spinomenal/FortunaDeLosMuertos3.webp",
    demo: 1,
    slug: "1030-fortuna-de-los-muertos-3-684",
    rtp: "55.5",
    no_dep_bonus: 0,
    lock_game: false,
  },
  {
    id: 17664,
    game_name: "Valentine Collection 40 Lines",
    provider: "Spinomenal",
    api_provider: "Ryan",
    thumbnail:
      "https://cdn2.softswiss.net/bets/i/s3/spinomenal/ValentineCollection40Lines.webp",
    demo: 1,
    slug: "491-valentine-collection-40-lines-868",
    rtp: null,
    no_dep_bonus: 0,
    lock_game: false,
  },
  {
    id: 36608,
    game_name: "The Ultimate 5",
    provider: "pragmaticplay",
    api_provider: "Ryan",
    thumbnail:
      "https://cdn2.softswiss.net/bets/i/s3/pragmaticexternal/TheUltimate5.webp",
    demo: 1,
    slug: "42503225-the-ultimate-5",
    rtp: "99.8",
    no_dep_bonus: 0,
    lock_game: false,
  },
  {
    id: 36864,
    game_name: "9 Gems",
    provider: "platipus",
    api_provider: "Ryan",
    thumbnail: "https://cdn2.softswiss.net/bets/i/s3/platipus/ninegems.webp",
    demo: 1,
    slug: "17399910-9-gems",
    rtp: "55.5",
    no_dep_bonus: 0,
    lock_game: false,
  },
  {
    id: 37888,
    game_name: "Hawaiian Night",
    provider: "platipus",
    api_provider: "Ryan",
    thumbnail: "https://cdn2.softswiss.net/i/s3/platipus/hawaiiannight.webp",
    demo: 1,
    slug: "45046926-hawaiian-night",
    rtp: null,
    no_dep_bonus: 0,
    lock_game: false,
  },
  {
    id: 38144,
    game_name: "Ragnawolves WildEnergy",
    provider: "Yggdrasil",
    api_provider: "Ryan",
    thumbnail:
      "https://cdn2.softswiss.net/i/s3/yggdrasil/RagnawolvesWildEnergy.webp",
    demo: 1,
    slug: "51266527-ragnawolves-wildenergy",
    rtp: null,
    no_dep_bonus: 0,
    lock_game: false,
  },
  {
    id: 41984,
    game_name: "Tai the Toad",
    provider: "Hacksaw",
    api_provider: "Ryan",
    thumbnail: "https://cdn2.softswiss.net/i/s3/hacksaw/TaitheToad96.webp",
    demo: 1,
    slug: "63242606-tai-the-toad",
    rtp: null,
    no_dep_bonus: 0,
    lock_game: false,
  },
  {
    id: 42240,
    game_name: "Legacy of Inca",
    provider: "PlayNgo",
    api_provider: "Ryan",
    thumbnail: "https://cdn2.softswiss.net/i/s3/playngo/LegacyofInca.webp",
    demo: 1,
    slug: "321014575-legacy-of-inca",
    rtp: null,
    no_dep_bonus: 1,
    lock_game: false,
  },
  {
    id: 17409,
    game_name: "Trout's Treasure - Fishing Season",
    provider: "Spinomenal",
    api_provider: "Ryan",
    thumbnail:
      "https://cdn2.softswiss.net/bets/i/s3/spinomenal/TroutsTreasureFishingSeason.webp",
    demo: 1,
    slug: "1029-trout's-treasure---fishing-season-910",
    rtp: null,
    no_dep_bonus: 0,
    lock_game: false,
  },
  {
    id: 17665,
    game_name: "Parrots Rock",
    provider: "Spinomenal",
    api_provider: "Ryan",
    thumbnail:
      "https://cdn2.softswiss.net/bets/i/s3/spinomenal/ParrotsRock.webp",
    demo: 1,
    slug: "490-parrots-rock-985",
    rtp: null,
    no_dep_bonus: 0,
    lock_game: false,
  },
];
